# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8acb6ec59c2afdb0db255f60f7e3af6c4fbaac438121d4abb518fa75c9290ad7bc543219bd8e44ceb690a4520997802dbc79b6aef5d80d7275637d46731fc470

test:
  secret_key_base: f050ae83f4dbb859d8c6840c6e1fce423d654ee00df3c1d277ef200bd6f71a0d3c17e10285f5fbf59cf04ea3831521d06cea1a2d48d9d2bacd6b6c04858d97f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
